package mocks

import "github.com/stretchr/testify/mock"

// PathModifier is an autogenerated mock type for the PathChecker type
type PathModifier struct {
	mock.Mock
}

// AbsPath provides a mock function with given fields: pth
func (_m *PathModifier) AbsPath(pth string) (string, error) {
	args := _m.Called(pth)
	var err error
	if len(args) > 1 {
		err = args.Error(1)
	}
	return args.String(0), err
}
